assignments/python/django/login/apps/users/urls.py
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<user_id>\d+)/show$', views.show, name='show'),
    url(r'^(?P<user_id>\d+)/edit$', views.edit, name="edit"),
]

assignments/python/django/login/login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.users.urls', namespace='users'))
]

assignments/python/django/login/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import bcrypt
from datetime import datetime
from ..pokes

class UserManager(models.Manager):
    def validate_and_create_user(self, form_data):
        errors = []

        if len(form_data['name']) < 3:
            errors.append(['funny name, ', form_data['name'], '!'])
        if len(form_data['user_name']) < 3:
            errors.append([form_data['user_name'], " ,that's what you call yourself!?"])
        if len(form_data['password']) < 3:
            errors.append("that ain't a password!")
        if not form_data['dob']:
            errors.append('you are not one of us, get out!') 
        if form_data['password'] != form_data['confirm']:
            errors.append("Only one password per person, that's the rule")
        if errors:
            return (False, errors)

        try:
            existing_user = self.get(user_name=form_data['user_name'])
            errors.append('User Name already exists.')
            return (False, errors)
        except:
            pw_hash = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
            dob = datetime.strptime(form_data['dob'],  '%Y-%m-%d').date()
            print "*"*20
            print len(pw_hash)
            user = self.create(
                name=form_data['name'], 
                user_name=form_data['user_name'],
                dob=dob,
                pw_hash=pw_hash
            )
            print "*"*30
            print user.id
            return (True, user.id)

    # def login(req):
    #     pass  
    
    # def modify(req):
    #     pass

class User(models.Model):
    name = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    dob = models.DateField()
    pw_hash = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    last_mod = models.DateTimeField(auto_now=True)
    objects = UserManager()


def __str__(self):
    return self.name

assignments/python/django/login/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages

from django.shortcuts import render, redirect, HttpResponse
from .models import User

def index(req):
  if 'user_id' not in req.session:
    return redirect('users:new')
  user_name = req.session['user_id']
  context = {
    'user': User.objects.get(user_name=user_name)
  }
  return render(req, 'users/index.html', context)

def create(req):
  if req.method != 'POST':
    return redirect('users:new')

  valid, result = User.objects.validate_and_create_user(req.POST)
  if not valid:
    for err in result:
      messages.error(req, err)
    return redirect('users:new')

  req.session['user_id'] = result
  return redirect('users:index')

def new(req):
    return render(req, 'users/new.html')

def show(req, user_id):
  if 'user_id' not in req.session:
    return redirect('users:new')

  try:
    user = User.objects.get(id=user_id)
  except:
    return redirect('users:index')

  context = {
    'user': User.objects.get(id=user_id)
  }

  return render(req, 'users/show.html', context)

def edit(req, user_id):
  if 'user_id' not in req.session:
    return redirect('users:new')

  try:
    user = User.objects.get(id=user_id)
  except:
    return redirect('users:index')

  context = {
    'user': user
  }
  return render(req, 'users/edit.html', context)
    

assignments/python/django/login/apps/users/templates/users/edit.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <h1>hiuwlahfulkejfjls</h1>
</body>
</html>

assignments/python/django/login/apps/users/templates/users/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>User Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>user name</th>
                <th>DOB</th>
                <th>ID</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.user_name }}</td>
                <td>{{ user.dob }}</td>
                <td>{{ user.id}}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>

assignments/python/django/login/apps/users/templates/users/new.html
<!DOCTYPE html>
<html>

<head>
    <title>user Index</title>
</head>

<body>
     {{request.session.user_id}}
    <h2>welcome</h2>
    <br> {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <h3>create an account or log in</h3>
    <hr>
    <form action="{% url 'users:create' %}" method="post">
        {% csrf_token %}
        <label for="name">Name</label>
        <br>
        <input type="text" name="name" placeholder="Sponge Bob">
        <br>
        <label for="user_name">User Name</label>
        <br>
        <input type="text" name="user_name" placeholder="Bob Sponge">
        <br>
        <label for="dob">Date od Birth</label>
        <br>
        <input type="date" name="dob">
        <br>
        <label for="password">password</label>
        <br>
        <input type="password" name="password" placeholder="your darkest secret ......">
        <br>
        <label for="confirm">confirm password</label>
        <br>
        <input type="password" name="confirm" placeholder="rubSomeBaconOnIt">
        <br>
        <input type="submit" value="Register">
    </form>
    <br>
    <h3>New User form</h3>
    <hr>
    <form  method="post">
        {% csrf_token %}
        <label for="user_name">User Name</label>
        <br>
        <input type="text" name="user_name">
        <br>
        <label for="password">password</label>
        <br>
        <input type="password" name="password">
        <br>
        <input type="submit" value="Login">
    </form>

</body>

</html>

assignments/python/django/login/apps/users/templates/users/show.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>User Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
    <h1>same old same old</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>user name</th>
                <th>DOB</th>
                <th>ID</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.user_name }}</td>
                <td>{{ user.dob }}</td>
                <td>{{ user.id}}</td>
            </tr>
        </tbody>
    </table>
    <a href="/{{ user.id }}/show" class="button">Edit User</a>
</body>

</html>